#pragma once
#include <maxapi.h>
#include <Qt/QMaxParamBlockWidget.h>
#include <QFileSystemWatcher>
#include "SceneController.h"
#include <QFileInfo>

// This namespace is defined in the header generated by Qt
namespace Ui {
	class RefMenuRollup;
};

// Inherit from QMaxParamBockWidget
class RefMenu :public QWidget
{
	// Connects us to Qt's meta-object system
	Q_OBJECT

public:
	RefMenu(QWidget * parent = nullptr);
	~RefMenu(void);

private:
	Ui::RefMenuRollup* ui;
	QString pathS;
	void OpenPathExplorer();
	void CreateButtonClicked();
	void RemoveButtonClicked();
	void AddFileWatcher();
	void AutoCheckBoxChanged(bool state);
	bool fileExists(QString path);
	QFileSystemWatcher *watcher;

public slots:
	void showModified(const QString& str);
};

